# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    # branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  labeler:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      repository-projects: read  

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Run a one-line script
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
        run: |
          labels=""
          for file in ${ALL_CHANGED_FILES}; do
            if [ "$(dirname ${file})" = "." ]; then
              label="root"
            else
              label="${file%%/*}"
            fi
            echo "[${file}] is changed dir:[$(dirname ${file})] label:${label}"
            labels="${labels}${label}\n"
          done
          echo "===LABELS==="
          echo $labels | sort -u | while read - ; do
            echo "LABEL: [${label}]"
          done
