# This is a auto labeler workflow
name: labeler

# Controls when the workflow will run
on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      repository-projects: read  

    steps:
      - uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44

      - name: List all changed files and label it
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          labels=""
          for file in ${ALL_CHANGED_FILES}; do
            if [ "$(dirname ${file})" = "." ]; then
              label="[root]"
            else
              label="${file%%/*}"
            fi
            # echo "[${file}] is changed dir:[$(dirname ${file})] label:${label}"
            labels="${labels}${label}\n"
          done
          echo -e "${labels}" | sort -u | while read label ; do
            if [ ! -z "${label}" ]; then
              echo "adding label: [${label}]"
              gh label create --force "${label}"
              gh pr edit "${PR_NUMBER}" --add-label "${label}"
            fi
          done
